export const products = [
  {
    id: 1,
    name: "House Mug",
    price: 9.99,
    image: "/images/house-mug.png",
    category: "mugs",
    brand: "CozyHome",
    rating: 4.5,
  },
  {
    id: 2,
    name: "Flower Mug",
    price: 9.99,
    image: "/images/flower-mug.png",
    category: "mugs",
    brand: "FloraCraft",
    rating: 4.8,
  },
  {
    id: 3,
    name: "Dad Mug",
    price: 9.99,
    image: "/images/dad-mug.png",
    category: "gifts",
    brand: "GiftedCo",
    rating: 4.3,
  },
  {
    id: 4,
    name: "It Was Never A Dress Mug",
    price: 19.99,
    image: "/images/mug-dress.png",
    category: "decor",
    brand: "StatementWare",
    rating: 4.9,
  },
  {
    id: 5,
    name: "Garlic Sauces",
    price: 20.99,
    image: "/images/garlic-sauces.png",
    category: "ingredients",
    brand: "KitchenPro",
    rating: 4.1,
  },
  {
    id: 6,
    name: "Whiskey Making Kit",
    price: 40.99,
    image: "/images/whiskey-kit.png",
    category: "gifts",
    brand: "CraftBarrel",
    rating: 4.7,
  },
];
