export const products = [
  {
    id: 1,
    name: "House Mug",
    price: 9.99,
    oldPrice: 12.99,
    image: "/images/house-mug.png",
    category: "mugs",
    brand: "CozyHome",
    rating: 4.5,
    description: "A cozy ceramic mug perfect for your morning coffee at home.",
  },
  {
    id: 2,
    name: "Flower Mug",
    price: 9.99,
    oldPrice: 11.99,
    image: "/images/flower-mug.png",
    category: "mugs",
    brand: "FloraCraft",
    rating: 4.8,
    description: "A delicate mug with a floral design to brighten your day.",
  },
  {
    id: 3,
    name: "Dad Mug",
    price: 9.99,
    oldPrice: 13.49,
    image: "/images/dad-mug.png",
    category: "gifts",
    brand: "GiftedCo",
    rating: 4.3,
    description: "A thoughtful mug gift for the best dad ever.",
  },
  {
    id: 4,
    name: "It Was Never A Dress Mug",
    price: 19.99,
    oldPrice: 24.99,
    image: "/images/mug-dress.png",
    category: "decor",
    brand: "StatementWare",
    rating: 4.9,
    description: "A bold and empowering statement mug for every occasion.",
  },
  {
    id: 5,
    name: "Garlic Sauces",
    price: 20.99,
    oldPrice: 26.99,
    image: "/images/garlic-sauces.png",
    category: "ingredients",
    brand: "KitchenPro",
    rating: 4.1,
    description: "A flavorful set of garlic sauces to elevate your dishes.",
  },
  {
    id: 6,
    name: "Whiskey Making Kit",
    price: 40.99,
    oldPrice: 49.99,
    image: "/images/whiskey-kit.png",
    category: "gifts",
    brand: "CraftBarrel",
    rating: 4.7,
    description: "Everything you need to craft your own whiskey at home.",
  },
];
