export const products = [
  {
    id: 1,
    name: "House Mug",
    price: 9.99,
    oldPrice: 12.99,
    image: "/images/house-mug.png",
    category: "Gifts",
    brand: "GiftedCo",
    rating: 4.5,
    description: "A cozy ceramic mug perfect for your morning coffee at home.",
  },
  {
    id: 2,
    name: "Flower Mug",
    price: 9.99,
    oldPrice: 11.99,
    image: "/images/flower-mug.png",
    category: "Gifts",
    brand: "GiftedCo",
    rating: 4.8,
    description: "A delicate mug with a floral design to brighten your day.",
  },
  {
    id: 3,
    name: "Dad Mug",
    price: 9.99,
    oldPrice: 13.49,
    image: "/images/dad-mug.png",
    category: "Gifts",
    brand: "GiftedCo",
    rating: 4.3,
    description: "A thoughtful mug gift for the best dad ever.",
  },
  {
    id: 4,
    name: "It Was Never A Dress Mug",
    price: 19.99,
    oldPrice: 24.99,
    image: "/images/mug-dress.png",
    category: "Gifts",
    brand: "StatementWare",
    rating: 4.9,
    description: "A bold and empowering statement mug for every occasion.",
  },
  {
    id: 5,
    name: "Garlic Sauces",
    price: 20.99,
    oldPrice: 26.99,
    image: "/images/garlic-sauces.png",
    category: "Kitchen & Bar",
    brand: "StatementWare",
    rating: 4.1,
    description: "A flavorful set of garlic sauces to elevate your dishes.",
  },
  {
    id: 6,
    name: "Whiskey Making Kit",
    price: 40.99,
    oldPrice: 49.99,
    image: "/images/whiskey-kit.png",
    category: "Gifts",
    brand: "StatementWare",
    rating: 4.7,
    description: "Everything you need to craft your own whiskey at home.",
  },
  {
    id: 7,
    name: "Solar Tealights",
    price: 44.99,
    oldPrice: 59.99,
    image: "/images/solar-tealights.png",
    category: "Home & Garden",
    brand: "CraftBarrel",
    rating: 4.3,
    description:
      "These colorful, swirled glass lamps glow after dark with solar-powered LED bulbs.",
  },
  {
    id: 8,
    name: "Jar Indoor Herb Garden",
    price: 20.99,
    oldPrice: 25.99,
    image: "/images/mason-jar.png",
    category: "Home & Garden",
    brand: "CraftBarrel",
    rating: 4.1,
    description:
      "These planters use a passive hydroponic system that makes it easy to grow your own herbs.",
  },
  {
    id: 9,
    name: "Birth Month Flower Glass",
    price: 26.99,
    oldPrice: 30.99,
    image: "/images/flower-glass.png",
    category: "Kitchen & Bar",
    brand: "CraftBarrel",
    rating: 5.0,
    description:
      "Toast your solar return all year long using glass with printed images of your birth flower.",
  },
  {
    id: 10,
    name: "Yellowstone Mug",
    price: 6.99,
    oldPrice: 9.99,
    image: "/images/yellowstone-mug.png",
    category: "Gifts",
    brand: "CraftBarrel",
    rating: 5.0,
    description:
      "Night falls and constellations glow on a moonlit addition to the Yellowstone mug.",
  },
  {
    id: 11,
    name: "Sweet Candles",
    price: 5.99,
    oldPrice: 9.99,
    image: "/images/sweet-candles.png",
    category: "Gifts",
    brand: "CraftBarrel",
    rating: 4.3,
    description:
      "Fill your space with warmth and comfort thanks to these hand-poured scented candles.",
  },
  {
    id: 12,
    name: "Who Is She Game",
    price: 26.99,
    oldPrice: 34.99,
    image: "/images/who-is-she.png",
    category: "Gifts",
    brand: "CraftBarrel",
    rating: 4.8,
    description:
      "A fun and engaging party game to test your wit and discover the mystery guest.",
  },
  {
    id: 13,
    name: "Weather Glass",
    price: 16.99,
    oldPrice: 24.99,
    image: "/images/weather-changing-glass.png",
    category: "Gifts",
    brand: "CraftBarrel",
    rating: 3.8,
    description:
      "An elegant glass that changes appearance based on the weather outside.",
  },
];
